#-------------------------------------------------------------------------------
# codegen.cmake - Autogenerated cmake containing generated classes
#-------------------------------------------------------------------------------

SET (scripts_dir ${CMAKE_CURRENT_SOURCE_DIR})

