#-------------------------------------------------------------------------------
# codegen.cmake - Autogenerated cmake containing generated classes
#-------------------------------------------------------------------------------

SET (scripts_dir ${CMAKE_CURRENT_SOURCE_DIR})

SET (scripts_codegen_SOURCES
  ${scripts_dir}/cmp/init.cmp
  ${scripts_dir}/cmp/gaen/lights.cmp
  ${scripts_dir}/cmp/gaen/shapes.cmp
  ${scripts_dir}/cmp/gaen/utils.cmp
  ${scripts_dir}/cpp/init.cpp
  ${scripts_dir}/cpp/gaen/lights.cpp
  ${scripts_dir}/cpp/gaen/shapes.cpp
  ${scripts_dir}/cpp/gaen/utils.cpp
)

IDE_SOURCE_PROPERTIES( "/cmp" "${scripts_dir}/cmp/init.cmp" )
IDE_SOURCE_PROPERTIES( "/cmp/gaen" "${scripts_dir}/cmp/gaen/lights.cmp" )
IDE_SOURCE_PROPERTIES( "/cmp/gaen" "${scripts_dir}/cmp/gaen/shapes.cmp" )
IDE_SOURCE_PROPERTIES( "/cmp/gaen" "${scripts_dir}/cmp/gaen/utils.cmp" )
IDE_SOURCE_PROPERTIES( "/cpp" "${scripts_dir}/cpp/init.cpp" )
IDE_SOURCE_PROPERTIES( "/cpp/gaen" "${scripts_dir}/cpp/gaen/lights.cpp" )
IDE_SOURCE_PROPERTIES( "/cpp/gaen" "${scripts_dir}/cpp/gaen/shapes.cpp" )
IDE_SOURCE_PROPERTIES( "/cpp/gaen" "${scripts_dir}/cpp/gaen/utils.cpp" )
