//------------------------------------------------------------------------------
// registration.cpp - Autogenerated from script Entities and Components
//------------------------------------------------------------------------------

#include "engine/Registry.h"

namespace gaen
{

void register_all_entities_and_components(Registry & registry)
{
}

} // namespace gaen
