//------------------------------------------------------------------------------
// Asset.h - Autogenerated message class for Asset
//
// Gaen Concurrency Engine - http://gaen.org
// Copyright (c) 2014-2016 Lachlan Orr
//
// This software is provided 'as-is', without any express or implied
// warranty. In no event will the authors be held liable for any damages
// arising from the use of this software.
//
// Permission is granted to anyone to use this software for any purpose,
// including commercial applications, and to alter it and redistribute it
// freely, subject to the following restrictions:
//
//   1. The origin of this software must not be misrepresented; you must not
//   claim that you wrote the original software. If you use this software
//   in a product, an acknowledgment in the product documentation would be
//   appreciated but is not required.
//
//   2. Altered source versions must be plainly marked as such, and must not be
//   misrepresented as being the original software.
//
//   3. This notice may not be removed or altered from any source
//   distribution.
//------------------------------------------------------------------------------

#ifndef GAEN_ENGINE_MESSAGES_ASSETMESSAGE_H
#define GAEN_ENGINE_MESSAGES_ASSETMESSAGE_H

#include "engine/MessageWriter.h"
#include "core/threading.h"
#include "engine/Task.h"
#include "engine/Model.h"
#include "engine/Handle.h"
#include "engine/Asset.h"

namespace gaen
{
namespace messages
{

template <typename T>
class AssetR
{
public:
    AssetR(const T & msgAcc)
      : mMsgAcc(msgAcc)
    {

    }

    Asset * asset() const { return static_cast<Asset *>(mMsgAcc[0].dCells[0].p); }
    u32 nameHash() const { return mMsgAcc[0].cells[2].u; }
    u32 taskId() const { return (u32)mMsgAcc.message().payload.u; }
        
private:
    AssetR(const AssetR &)              = delete;
    AssetR(const AssetR &&)             = delete;
    AssetR & operator=(const AssetR &)  = delete;
    AssetR & operator=(const AssetR &&) = delete;

    const T & mMsgAcc;


};

typedef AssetR<MessageQueueAccessor> AssetQR;
typedef AssetR<MessageBlockAccessor> AssetBR;

class AssetQW : public MessageQueueWriter
{
public:
    AssetQW(u32 msgId,
            u32 flags,
            task_id source,
            task_id target,
            u32 taskId)
      : MessageQueueWriter(msgId,
                           flags,
                           source,
                           target,
                           to_cell(taskId),
                           1)
    {}

    AssetQW(u32 msgId,
            u32 flags,
            task_id source,
            task_id target,
            u32 taskId,
            MessageQueue * pMsgQueue)
      : MessageQueueWriter(msgId,
                           flags,
                           source,
                           target,
                           to_cell(taskId),
                           1,
                           pMsgQueue)
    {}
    
    void setAsset(Asset * pVal) { mMsgAcc[0].dCells[0].p = (void*)pVal; }
    void setNameHash(u32 val) { mMsgAcc[0].cells[2].u = val; }
    void setTaskId(u32 val) { mMsgAcc.message().payload.u = (u32)val; }
private:
    AssetQW(const AssetQW &)              = delete;
    AssetQW(const AssetQW &&)             = delete;
    AssetQW & operator=(const AssetQW &)  = delete;
    AssetQW & operator=(const AssetQW &&) = delete;
};

class AssetBW : public MessageBlockWriter
{
public:
    AssetBW(u32 msgId,
            u32 flags,
            task_id source,
            task_id target,
            u32 taskId)
      : MessageBlockWriter(msgId,
                           flags,
                           source,
                           target,
                           to_cell(taskId),
                           1,
                           mBlocks)
    {}

    void setAsset(Asset * pVal) { mMsgAcc[0].dCells[0].p = (void*)pVal; }
    void setNameHash(u32 val) { mMsgAcc[0].cells[2].u = val; }
    void setTaskId(u32 val) { mMsgAcc.message().payload.u = (u32)val; }

private:
    AssetBW(const AssetBW &)              = delete;
    AssetBW(const AssetBW &&)             = delete;
    AssetBW & operator=(const AssetBW &)  = delete;
    AssetBW & operator=(const AssetBW &&) = delete;

    Block mBlocks[1 + 1]; // +1 for header
};

} // namespace msg
} // namespace gaen

#endif // #ifndef GAEN_ENGINE_MESSAGES_ASSETMESSAGE_H

