//------------------------------------------------------------------------------
// Handle.h - Autogenerated message class for Handle
//
// Gaen Concurrency Engine - http://gaen.org
// Copyright (c) 2014-2016 Lachlan Orr
//
// This software is provided 'as-is', without any express or implied
// warranty. In no event will the authors be held liable for any damages
// arising from the use of this software.
//
// Permission is granted to anyone to use this software for any purpose,
// including commercial applications, and to alter it and redistribute it
// freely, subject to the following restrictions:
//
//   1. The origin of this software must not be misrepresented; you must not
//   claim that you wrote the original software. If you use this software
//   in a product, an acknowledgment in the product documentation would be
//   appreciated but is not required.
//
//   2. Altered source versions must be plainly marked as such, and must not be
//   misrepresented as being the original software.
//
//   3. This notice may not be removed or altered from any source
//   distribution.
//------------------------------------------------------------------------------

#ifndef GAEN_ENGINE_MESSAGES_HANDLEMESSAGE_H
#define GAEN_ENGINE_MESSAGES_HANDLEMESSAGE_H

#include "engine/MessageWriter.h"
#include "core/threading.h"
#include "engine/Model.h"
#include "engine/Handle.h"

namespace gaen
{
namespace messages
{

template <typename T>
class HandleR
{
public:
    HandleR(const T & msgAcc)
      : mMsgAcc(msgAcc)
    {

    }

    Handle * handle() const { return static_cast<Handle *>(mMsgAcc[0].dCells[0].p); }
        
private:
    const T & mMsgAcc;


};

typedef HandleR<MessageQueueAccessor> HandleQR;
typedef HandleR<MessageBlockAccessor> HandleBR;

class HandleQW : public MessageQueueWriter
{
public:
    HandleQW(u32 msgId,
             u32 flags,
             task_id source,
             task_id target)
      : MessageQueueWriter(msgId,
                           flags,
                           source,
                           target,
                           to_cell(0),
                           1)
    {}
    
    void setHandle(Handle * pVal) { mMsgAcc[0].dCells[0].p = pVal; }
};

class HandleBW : public MessageBlockWriter
{
public:
    HandleBW(u32 msgId,
             u32 flags,
             task_id source,
             task_id target)
      : MessageBlockWriter(msgId,
                           flags,
                           source,
                           target,
                           to_cell(0),
                           1,
                           mBlocks)
    {}

    void setHandle(Handle * pVal) { mMsgAcc[0].dCells[0].p = pVal; }

private:
    Block mBlocks[1 + 1]; // +1 for header
};

} // namespace msg
} // namespace gaen

#endif // #ifndef GAEN_ENGINE_MESSAGES_HANDLEMESSAGE_H

