* Gaen Concurrency Engine
A cross platform, [[http://en.wikipedia.org/wiki/Entity_component_system][component based game engine]] that automates CPU
concurrency.

Game designers create components and entities and designate data
dependencies. The engine load balances these entities across all
available cores. Running on a machine with more cores will
automatically improve performance without any code modifications.

Gaen is licensed under the terms of the [[http://en.wikipedia.org/wiki/Zlib_License][zlib License]].

**  Compose Scripting Language
To enable rapid prototyping and empower non-C++ programmers to create
with Gaen, there is Compose. It is a C-like language with lots of
syntactic sugar around components, entities and message passing. It
eliminates the boiler plate verbosity that comes with forcing C++ into
a message passing, component based model.

The language can be interpreted in a VM for rapid prototyping, or
compiled into C++ for maximum performance after the scripts have been
written and tested.

** Platforms
Active development is for Windows, but the engine is designed to run
on OSX and Linux as well. Development started on OSX, so support is
pretty well established there. Linux will require some porting work of
small chunks of isolated code. AMD64 is assumed, but it should not be
too hard to move to another 64 bit architecture.

[[http://en.wikipedia.org/wiki/C++11][C++11]] features are used extensively, so you must have a recent
compiler.  On Windows this means VC 2013 or above. On OSX and Linux,
GCC 4.8 is recommended.

** Building
The build system is CMake based, which makes possible the generation
of VS Projects on Windows and make files on OSX and Linux. To run
CMake, run either bootstrap.bat or bootstrap.sh from the gaen
directory and it will place generated files in gaen/build. To
completely clean the build and start from scratch, run clean.bat or
clean.sh.

*** Building on OSX Mavericks
OSX is using makefiles and not Xcode. I found it a bit obtuse to get
C++11 compiler support in Xcode, so I abandoned the effort. I also do
not appreciate the cruft Xcode places in the generated bundle. The
package that comes out of the makefile process is much cleaner. CMake
enables the generation of Xcode projects, but the compiler issues will
have to be solved.

**** Notes on building in OSX Mavericks
1. Install GCC 4.8 through homebrew.
2. Add a setcc.sh in root gaen directory containing something like:
   #+BEGIN_SRC sh
   export CC=/usr/local/bin/gcc-4.8
   export CXX=/usr/local/bin/g++-4.8
   #+END_SRC
3. Run bootstrap.sh
4. Make in build/Debug

You may need to apply this patch to /usr/include/sys/cdefs.h:

#+BEGIN_SRC shell
--- /usr/include/sys/cdefs.h.original	2014-01-11 20:47:05.000000000 -0600
+++ /usr/include/sys/cdefs.h	2014-01-11 20:48:51.000000000 -0600
@@ -216,7 +216,7 @@

 #if __STDC_VERSION__ >= 199901L && (!defined(__GNUC__) || defined(__clang__))
 # define __header_inline           inline
-#elif defined(__GNUC__) && defined(__GNUC_STDC_INLINE__)
+#elif defined(__GNUC__) && defined(__GNUC_STDC_INLINE__) && !defined(__cplusplus)
 # define __header_inline           extern __inline __attribute__((__gnu_inline__))
 #elif defined(__GNUC__)
 # define __header_inline           extern __inline
#+END_SRC

***** To use gdb on Mavericks, read this. What a pain, Apple:
http://wiki.lazarus.freepascal.org/GDB_on_OS_X_Mavericks_and_Xcode_5

