#-------------------------------------------------------------------------------
# codegen.cmake - Autogenerated cmake containing generated classes
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
# 
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
# 
#   1. The origin of this software must not be misrepresented; you must not
#   claim that you wrote the original software. If you use this software
#   in a product, an acknowledgment in the product documentation would be
#   appreciated but is not required.
# 
#   2. Altered source versions must be plainly marked as such, and must not be
#   misrepresented as being the original software.
# 
#   3. This notice may not be removed or altered from any source
#   distribution.
#-------------------------------------------------------------------------------

SET (scripts_dir C:/code/gaen/src/scripts)

SET (scripts_codegen_SOURCES
  ${scripts_dir}/cmp/start.cmp
  ${scripts_dir}/cmp/lib/model.cmp
  ${scripts_dir}/cmp/utils/Timer.cmp
  ${scripts_dir}/cpp/start.cpp
  ${scripts_dir}/cpp/lib/model.cpp
  ${scripts_dir}/cpp/utils/Timer.cpp
  ${scripts_dir}/cpp/lib/model.h
)

IDE_SOURCE_PROPERTIES( "/cmp" "${scripts_dir}/cmp/start.cmp" )
IDE_SOURCE_PROPERTIES( "/cmp/lib" "${scripts_dir}/cmp/lib/model.cmp" )
IDE_SOURCE_PROPERTIES( "/cmp/utils" "${scripts_dir}/cmp/utils/Timer.cmp" )
IDE_SOURCE_PROPERTIES( "/cpp" "${scripts_dir}/cpp/start.cpp" )
IDE_SOURCE_PROPERTIES( "/cpp/lib" "${scripts_dir}/cpp/lib/model.cpp" )
IDE_SOURCE_PROPERTIES( "/cpp/utils" "${scripts_dir}/cpp/utils/Timer.cpp" )
IDE_SOURCE_PROPERTIES( "/cpp/lib" "${scripts_dir}/cpp/lib/model.h" )
