#-------------------------------------------------------------------------------
# codegen.cmake - Autogenerated cmake containing generated classes
#
# Gaen Concurrency Engine - http://gaen.org
# Copyright (c) 2014-2015 Lachlan Orr
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
#   1. The origin of this software must not be misrepresented; you must not
#   claim that you wrote the original software. If you use this software
#   in a product, an acknowledgment in the product documentation would be
#   appreciated but is not required.
#
#   2. Altered source versions must be plainly marked as such, and must not be
#   misrepresented as being the original software.
#
#   3. This notice may not be removed or altered from any source
#   distribution.
#-------------------------------------------------------------------------------

SET (scripts_dir ${CMAKE_CURRENT_SOURCE_DIR})

SET (scripts_codegen_SOURCES
  ${scripts_dir}/cmp/init.cmp
  ${scripts_dir}/cmp/lights.cmp
  ${scripts_dir}/cmp/shapes.cmp
  ${scripts_dir}/cmp/test.cmp
  ${scripts_dir}/cmp/utils.cmp
  ${scripts_dir}/cpp/init.cpp
  ${scripts_dir}/cpp/lights.cpp
  ${scripts_dir}/cpp/shapes.cpp
  ${scripts_dir}/cpp/test.cpp
  ${scripts_dir}/cpp/utils.cpp
)

IDE_SOURCE_PROPERTIES( "/cmp" "${scripts_dir}/cmp/init.cmp" )
IDE_SOURCE_PROPERTIES( "/cmp" "${scripts_dir}/cmp/lights.cmp" )
IDE_SOURCE_PROPERTIES( "/cmp" "${scripts_dir}/cmp/shapes.cmp" )
IDE_SOURCE_PROPERTIES( "/cmp" "${scripts_dir}/cmp/test.cmp" )
IDE_SOURCE_PROPERTIES( "/cmp" "${scripts_dir}/cmp/utils.cmp" )
IDE_SOURCE_PROPERTIES( "/cpp" "${scripts_dir}/cpp/init.cpp" )
IDE_SOURCE_PROPERTIES( "/cpp" "${scripts_dir}/cpp/lights.cpp" )
IDE_SOURCE_PROPERTIES( "/cpp" "${scripts_dir}/cpp/shapes.cpp" )
IDE_SOURCE_PROPERTIES( "/cpp" "${scripts_dir}/cpp/test.cpp" )
IDE_SOURCE_PROPERTIES( "/cpp" "${scripts_dir}/cpp/utils.cpp" )
